# Generated by Django 5.2.1 on 2025-05-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='description_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='name_kk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
